export type PhoneCode = {
  mask: string
  cc: string | string[]
  cd: string
}

export const PHONE_CODES = [
  { mask: "+247-####", cc: "AC", cd: "Ascension" },
  { mask: "+376-###-###", cc: "AD", cd: "Andorra" },
  { mask: "+971-5#-###-####", cc: "AE", cd: "United Arab Emirates" },
  { mask: "+971-#-###-####", cc: "AE", cd: "United Arab Emirates" },
  { mask: "+93-##-###-####", cc: "AF", cd: "Afghanistan" },
  { mask: "+1(268)###-####", cc: "AG", cd: "Antigua & Barbuda" },
  { mask: "+1(264)###-####", cc: "AI", cd: "Anguilla" },
  { mask: "+355(###)###-###", cc: "AL", cd: "Albania" },
  { mask: "+374-##-###-###", cc: "AM", cd: "Armenia" },
  { mask: "+599-###-####", cc: "AN", cd: "Caribbean Netherlands" },
  { mask: "+599-###-####", cc: "AN", cd: "Netherlands Antilles" },
  { mask: "+599-9###-####", cc: "AN", cd: "Netherlands Antilles" },
  { mask: "+244(###)###-###", cc: "AO", cd: "Angola" },
  { mask: "+672-1##-###", cc: "AQ", cd: "Australian bases in Antarctica" },
  { mask: "+54(###)###-####", cc: "AR", cd: "Argentina" },
  { mask: "+1(684)###-####", cc: "AS", cd: "American Samoa" },
  { mask: "+43(###)###-####", cc: "AT", cd: "Austria" },
  { mask: "+61-#-####-####", cc: "AU", cd: "Australia" },
  { mask: "+297-###-####", cc: "AW", cd: "Aruba" },
  { mask: "+994-##-###-##-##", cc: "AZ", cd: "Azerbaijan" },
  { mask: "+387-##-#####", cc: "BA", cd: "Bosnia and Herzegovina" },
  { mask: "+387-##-####", cc: "BA", cd: "Bosnia and Herzegovina" },
  { mask: "+1(246)###-####", cc: "BB", cd: "Barbados" },
  { mask: "+880-##-###-###", cc: "BD", cd: "Bangladesh" },
  { mask: "+32(###)###-###", cc: "BE", cd: "Belgium" },
  { mask: "+226-##-##-####", cc: "BF", cd: "Burkina Faso" },
  { mask: "+359(###)###-###", cc: "BG", cd: "Bulgaria" },
  { mask: "+973-####-####", cc: "BH", cd: "Bahrain" },
  { mask: "+257-##-##-####", cc: "BI", cd: "Burundi" },
  { mask: "+229-##-##-####", cc: "BJ", cd: "Benin" },
  { mask: "+1(441)###-####", cc: "BM", cd: "Bermuda" },
  { mask: "+673-###-####", cc: "BN", cd: "Brunei Darussalam" },
  { mask: "+591-#-###-####", cc: "BO", cd: "Bolivia" },
  { mask: "+55-##-####-####", cc: "BR", cd: "Brazil" },
  { mask: "+55-##-#####-####", cc: "BR", cd: "Brazil" },
  { mask: "+1(242)###-####", cc: "BS", cd: "Bahamas" },
  { mask: "+975-17-###-###", cc: "BT", cd: "Bhutan" },
  { mask: "+975-#-###-###", cc: "BT", cd: "Bhutan" },
  { mask: "+267-##-###-###", cc: "BW", cd: "Botswana" },
  { mask: "+375(##)###-##-##", cc: "BY", cd: "Belarus" },
  { mask: "+501-###-####", cc: "BZ", cd: "Belize" },
  { mask: "+243(###)###-###", cc: "CD", cd: "Dem. Rep. Congo" },
  { mask: "+236-##-##-####", cc: "CF", cd: "Central African Republic" },
  { mask: "+242-##-###-####", cc: "CG", cd: "Congo (Brazzaville)" },
  { mask: "+41-##-###-####", cc: "CH", cd: "Switzerland" },
  { mask: "+225-##-###-###", cc: "CI", cd: "Cote d’Ivoire (Ivory Coast)" },
  { mask: "+682-##-###", cc: "CK", cd: "Cook Islands" },
  { mask: "+56-#-####-####", cc: "CL", cd: "Chile" },
  { mask: "+237-####-####", cc: "CM", cd: "Cameroon" },
  { mask: "+86(###)####-####", cc: "CN", cd: "China (PRC)" },
  { mask: "+86(###)####-###", cc: "CN", cd: "China (PRC)" },
  { mask: "+86-##-#####-#####", cc: "CN", cd: "China (PRC)" },
  { mask: "+57(###)###-####", cc: "CO", cd: "Colombia" },
  { mask: "+506-####-####", cc: "CR", cd: "Costa Rica" },
  { mask: "+53-#-###-####", cc: "CU", cd: "Cuba" },
  { mask: "+238(###)##-##", cc: "CV", cd: "Cape Verde" },
  { mask: "+599-###-####", cc: "CW", cd: "Curacao" },
  { mask: "+357-##-###-###", cc: "CY", cd: "Cyprus" },
  { mask: "+420(###)###-###", cc: "CZ", cd: "Czech Republic" },
  { mask: "+49(####)###-####", cc: "DE", cd: "Germany" },
  { mask: "+49(###)###-####", cc: "DE", cd: "Germany" },
  { mask: "+49(###)##-####", cc: "DE", cd: "Germany" },
  { mask: "+49(###)##-###", cc: "DE", cd: "Germany" },
  { mask: "+49(###)##-##", cc: "DE", cd: "Germany" },
  { mask: "+49-###-###", cc: "DE", cd: "Germany" },
  { mask: "+253-##-##-##-##", cc: "DJ", cd: "Djibouti" },
  { mask: "+45-##-##-##-##", cc: "DK", cd: "Denmark" },
  { mask: "+1(767)###-####", cc: "DM", cd: "Dominica" },
  { mask: "+1(809)###-####", cc: "DO", cd: "Dominican Republic" },
  { mask: "+1(829)###-####", cc: "DO", cd: "Dominican Republic" },
  { mask: "+1(849)###-####", cc: "DO", cd: "Dominican Republic" },
  { mask: "+213-##-###-####", cc: "DZ", cd: "Algeria" },
  { mask: "+593-##-###-####", cc: "EC", cd: "Ecuador " },
  { mask: "+593-#-###-####", cc: "EC", cd: "Ecuador" },
  { mask: "+372-####-####", cc: "EE", cd: "Estonia " },
  { mask: "+372-###-####", cc: "EE", cd: "Estonia" },
  { mask: "+20(###)###-####", cc: "EG", cd: "Egypt" },
  { mask: "+291-#-###-###", cc: "ER", cd: "Eritrea" },
  { mask: "+34(###)###-###", cc: "ES", cd: "Spain" },
  { mask: "+251-##-###-####", cc: "ET", cd: "Ethiopia" },
  { mask: "+358(###)###-##-##", cc: "FI", cd: "Finland" },
  { mask: "+679-##-#####", cc: "FJ", cd: "Fiji" },
  { mask: "+500-#####", cc: "FK", cd: "Falkland Islands" },
  { mask: "+691-###-####", cc: "FM", cd: "F.S. Micronesia" },
  { mask: "+298-###-###", cc: "FO", cd: "Faroe Islands" },
  { mask: "+262-#####-####", cc: "FR", cd: "Mayotte" },
  { mask: "+33(###)###-###", cc: "FR", cd: "France" },
  { mask: "+508-##-####", cc: "FR", cd: "St Pierre & Miquelon" },
  { mask: "+590(###)###-###", cc: "FR", cd: "Guadeloupe" },
  { mask: "+241-#-##-##-##", cc: "GA", cd: "Gabon" },
  { mask: "+1(473)###-####", cc: "GD", cd: "Grenada" },
  { mask: "+995(###)###-###", cc: "GE", cd: "Rep. of Georgia" },
  { mask: "+594-#####-####", cc: "GF", cd: "Guiana (French)" },
  { mask: "+233(###)###-###", cc: "GH", cd: "Ghana" },
  { mask: "+350-###-#####", cc: "GI", cd: "Gibraltar" },
  { mask: "+299-##-##-##", cc: "GL", cd: "Greenland" },
  { mask: "+220(###)##-##", cc: "GM", cd: "Gambia" },
  { mask: "+224-##-###-###", cc: "GN", cd: "Guinea" },
  { mask: "+240-##-###-####", cc: "GQ", cd: "Equatorial Guinea" },
  { mask: "+30(###)###-####", cc: "GR", cd: "Greece" },
  { mask: "+502-#-###-####", cc: "GT", cd: "Guatemala" },
  { mask: "+1(671)###-####", cc: "GU", cd: "Guam" },
  { mask: "+245-#-######", cc: "GW", cd: "Guinea-Bissau" },
  { mask: "+592-###-####", cc: "GY", cd: "Guyana" },
  { mask: "+852-####-####", cc: "HK", cd: "Hong Kong" },
  { mask: "+504-####-####", cc: "HN", cd: "Honduras" },
  { mask: "+385-(##)-###-###", cc: "HR", cd: "Croatia" },
  { mask: "+385-(##)-###-####", cc: "HR", cd: "Croatia" },
  { mask: "+385-1-####-###", cc: "HR", cd: "Croatia" },
  { mask: "+509-##-##-####", cc: "HT", cd: "Haiti" },
  { mask: "+36(###)###-###", cc: "HU", cd: "Hungary" },
  { mask: "+62(8##)###-####", cc: "ID", cd: "Indonesia " },
  { mask: "+62-##-###-##", cc: "ID", cd: "Indonesia" },
  { mask: "+62-##-###-###", cc: "ID", cd: "Indonesia" },
  { mask: "+62-##-###-####", cc: "ID", cd: "Indonesia" },
  { mask: "+62(8##)###-###", cc: "ID", cd: "Indonesia " },
  { mask: "+62(8##)###-##-###", cc: "ID", cd: "Indonesia " },
  { mask: "+353(###)###-###", cc: "IE", cd: "Ireland" },
  { mask: "+972-5#-###-####", cc: "IL", cd: "Israel " },
  { mask: "+972-#-###-####", cc: "IL", cd: "Israel" },
  { mask: "+91(####)###-###", cc: "IN", cd: "India" },
  { mask: "+246-###-####", cc: "IO", cd: "Diego Garcia" },
  { mask: "+964(###)###-####", cc: "IQ", cd: "Iraq" },
  { mask: "+98(###)###-####", cc: "IR", cd: "Iran" },
  { mask: "+354-###-####", cc: "IS", cd: "Iceland" },
  { mask: "+39(0##)####-##-##", cc: "IT", cd: "Italy" },
  { mask: "+39(0##)####-###", cc: "IT", cd: "Italy" },
  { mask: "+39(0##)###-###", cc: "IT", cd: "Italy" },
  { mask: "+39(0##)##-###", cc: "IT", cd: "Italy" },
  { mask: "+39(0##)##-##", cc: "IT", cd: "Italy" },
  { mask: "+39(0#)##-##", cc: "IT", cd: "Italy" },
  { mask: "+39(3##)###-##-##", cc: "IT", cd: "Italy" },
  { mask: "+39(3##)##-##-##", cc: "IT", cd: "Italy" },
  { mask: "+1(876)###-####", cc: "JM", cd: "Jamaica" },
  { mask: "+962-#-####-####", cc: "JO", cd: "Jordan" },
  { mask: "+81-##-####-####", cc: "JP", cd: "Japan " },
  { mask: "+81(###)###-###", cc: "JP", cd: "Japan" },
  { mask: "+254-###-######", cc: "KE", cd: "Kenya" },
  { mask: "+996(###)###-###", cc: "KG", cd: "Kyrgyzstan" },
  { mask: "+855-##-###-###", cc: "KH", cd: "Cambodia" },
  { mask: "+686-##-###", cc: "KI", cd: "Kiribati" },
  { mask: "+269-##-#####", cc: "KM", cd: "Comoros" },
  { mask: "+1(869)###-####", cc: "KN", cd: "Saint Kitts & Nevis" },
  { mask: "+850-191-###-####", cc: "KP", cd: "DPR Korea (North) " },
  { mask: "+850-##-###-###", cc: "KP", cd: "DPR Korea (North)" },
  { mask: "+850-###-####-###", cc: "KP", cd: "DPR Korea (North)" },
  { mask: "+850-###-###", cc: "KP", cd: "DPR Korea (North)" },
  { mask: "+850-####-####", cc: "KP", cd: "DPR Korea (North)" },
  { mask: "+850-####-#############", cc: "KP", cd: "DPR Korea (North)" },
  { mask: "+82-##-###-####", cc: "KR", cd: "Korea (South)" },
  { mask: "+965-####-####", cc: "KW", cd: "Kuwait" },
  { mask: "+1(345)###-####", cc: "KY", cd: "Cayman Islands" },
  { mask: "+7(6##)###-##-##", cc: "KZ", cd: "Kazakhstan" },
  { mask: "+7(7##)###-##-##", cc: "KZ", cd: "Kazakhstan" },
  { mask: "+856(20##)###-###", cc: "LA", cd: "Laos " },
  { mask: "+856-##-###-###", cc: "LA", cd: "Laos" },
  { mask: "+961-##-###-###", cc: "LB", cd: "Lebanon " },
  { mask: "+961-#-###-###", cc: "LB", cd: "Lebanon" },
  { mask: "+1(758)###-####", cc: "LC", cd: "Saint Lucia" },
  { mask: "+423(###)###-####", cc: "LI", cd: "Liechtenstein" },
  { mask: "+94-##-###-####", cc: "LK", cd: "Sri Lanka" },
  { mask: "+231-##-###-###", cc: "LR", cd: "Liberia" },
  { mask: "+266-#-###-####", cc: "LS", cd: "Lesotho" },
  { mask: "+370(###)##-###", cc: "LT", cd: "Lithuania" },
  { mask: "+352-###-###", cc: "LU", cd: "Luxembourg" },
  { mask: "+352-####-###", cc: "LU", cd: "Luxembourg" },
  { mask: "+352-#####-###", cc: "LU", cd: "Luxembourg" },
  { mask: "+352-######-###", cc: "LU", cd: "Luxembourg" },
  { mask: "+371-##-###-###", cc: "LV", cd: "Latvia" },
  { mask: "+218-##-###-###", cc: "LY", cd: "Libya" },
  { mask: "+218-21-###-####", cc: "LY", cd: "Libya" },
  { mask: "+212-##-####-###", cc: "MA", cd: "Morocco" },
  { mask: "+377(###)###-###", cc: "MC", cd: "Monaco" },
  { mask: "+377-##-###-###", cc: "MC", cd: "Monaco" },
  { mask: "+373-####-####", cc: "MD", cd: "Moldova" },
  { mask: "+382-##-###-###", cc: "ME", cd: "Montenegro" },
  { mask: "+261-##-##-#####", cc: "MG", cd: "Madagascar" },
  { mask: "+692-###-####", cc: "MH", cd: "Marshall Islands" },
  { mask: "+389-##-###-###", cc: "MK", cd: "Republic of Macedonia" },
  { mask: "+223-##-##-####", cc: "ML", cd: "Mali" },
  { mask: "+95-##-###-###", cc: "MM", cd: "Burma (Myanmar)" },
  { mask: "+95-#-###-###", cc: "MM", cd: "Burma (Myanmar)" },
  { mask: "+95-###-###", cc: "MM", cd: "Burma (Myanmar)" },
  { mask: "+976-##-##-####", cc: "MN", cd: "Mongolia" },
  { mask: "+853-####-####", cc: "MO", cd: "Macau" },
  { mask: "+1(670)###-####", cc: "MP", cd: "Northern Mariana Islands" },
  { mask: "+596(###)##-##-##", cc: "MQ", cd: "Martinique" },
  { mask: "+222-##-##-####", cc: "MR", cd: "Mauritania" },
  { mask: "+1(664)###-####", cc: "MS", cd: "Montserrat" },
  { mask: "+356-####-####", cc: "MT", cd: "Malta" },
  { mask: "+230-###-####", cc: "MU", cd: "Mauritius" },
  { mask: "+960-###-####", cc: "MV", cd: "Maldives" },
  { mask: "+265-1-###-###", cc: "MW", cd: "Malawi" },
  { mask: "+265-#-####-####", cc: "MW", cd: "Malawi" },
  { mask: "+52(###)###-####", cc: "MX", cd: "Mexico" },
  { mask: "+52-##-##-####", cc: "MX", cd: "Mexico" },
  { mask: "+60-##-###-####", cc: "MY", cd: "Malaysia " },
  { mask: "+60-11-####-####", cc: "MY", cd: "Malaysia " },
  { mask: "+60(###)###-###", cc: "MY", cd: "Malaysia" },
  { mask: "+60-##-###-###", cc: "MY", cd: "Malaysia" },
  { mask: "+60-#-###-###", cc: "MY", cd: "Malaysia" },
  { mask: "+258-##-###-###", cc: "MZ", cd: "Mozambique" },
  { mask: "+264-##-###-####", cc: "NA", cd: "Namibia" },
  { mask: "+687-##-####", cc: "NC", cd: "New Caledonia" },
  { mask: "+227-##-##-####", cc: "NE", cd: "Niger" },
  { mask: "+672-3##-###", cc: "NF", cd: "Norfolk Island" },
  { mask: "+234(###)###-####", cc: "NG", cd: "Nigeria" },
  { mask: "+234-##-###-###", cc: "NG", cd: "Nigeria" },
  { mask: "+234-##-###-##", cc: "NG", cd: "Nigeria" },
  { mask: "+234(###)###-####", cc: "NG", cd: "Nigeria " },
  { mask: "+505-####-####", cc: "NI", cd: "Nicaragua" },
  { mask: "+31-##-###-####", cc: "NL", cd: "Netherlands" },
  { mask: "+47(###)##-###", cc: "NO", cd: "Norway" },
  { mask: "+977-##-###-###", cc: "NP", cd: "Nepal" },
  { mask: "+674-###-####", cc: "NR", cd: "Nauru" },
  { mask: "+683-####", cc: "NU", cd: "Niue" },
  { mask: "+64(###)###-###", cc: "NZ", cd: "New Zealand" },
  { mask: "+64-##-###-###", cc: "NZ", cd: "New Zealand" },
  { mask: "+64(###)###-####", cc: "NZ", cd: "New Zealand" },
  { mask: "+968-##-###-###", cc: "OM", cd: "Oman" },
  { mask: "+507-###-####", cc: "PA", cd: "Panama" },
  { mask: "+51(###)###-###", cc: "PE", cd: "Peru" },
  { mask: "+689-##-##-##", cc: "PF", cd: "French Polynesia" },
  { mask: "+675(###)##-###", cc: "PG", cd: "Papua New Guinea" },
  { mask: "+63(###)###-####", cc: "PH", cd: "Philippines" },
  { mask: "+92(###)###-####", cc: "PK", cd: "Pakistan" },
  { mask: "+48(###)###-###", cc: "PL", cd: "Poland" },
  { mask: "+970-##-###-####", cc: "PS", cd: "Palestine" },
  { mask: "+351-##-###-####", cc: "PT", cd: "Portugal" },
  { mask: "+680-###-####", cc: "PW", cd: "Palau" },
  { mask: "+595(###)###-###", cc: "PY", cd: "Paraguay" },
  { mask: "+974-####-####", cc: "QA", cd: "Qatar" },
  { mask: "+262-#####-####", cc: "RE", cd: "Reunion" },
  { mask: "+40-##-###-####", cc: "RO", cd: "Romania" },
  { mask: "+381-##-###-####", cc: "RS", cd: "Serbia" },
  { mask: "+7(###)###-##-##", cc: "RU", cd: "Russia" },
  { mask: "+250(###)###-###", cc: "RW", cd: "Rwanda" },
  { mask: "+966-5-####-####", cc: "SA", cd: "Saudi Arabia " },
  { mask: "+966-#-###-####", cc: "SA", cd: "Saudi Arabia" },
  { mask: "+677-###-####", cc: "SB", cd: "Solomon Islands " },
  { mask: "+677-#####", cc: "SB", cd: "Solomon Islands" },
  { mask: "+248-#-###-###", cc: "SC", cd: "Seychelles" },
  { mask: "+249-##-###-####", cc: "SD", cd: "Sudan" },
  { mask: "+46-##-###-####", cc: "SE", cd: "Sweden" },
  { mask: "+65-####-####", cc: "SG", cd: "Singapore" },
  { mask: "+290-####", cc: "SH", cd: "Saint Helena" },
  { mask: "+290-####", cc: "SH", cd: "Tristan da Cunha" },
  { mask: "+386-##-###-###", cc: "SI", cd: "Slovenia" },
  { mask: "+421(###)###-###", cc: "SK", cd: "Slovakia" },
  { mask: "+232-##-######", cc: "SL", cd: "Sierra Leone" },
  { mask: "+378-####-######", cc: "SM", cd: "San Marino" },
  { mask: "+221-##-###-####", cc: "SN", cd: "Senegal" },
  { mask: "+252-##-###-###", cc: "SO", cd: "Somalia" },
  { mask: "+252-#-###-###", cc: "SO", cd: "Somalia" },
  { mask: "+252-#-###-###", cc: "SO", cd: "Somalia " },
  { mask: "+597-###-####", cc: "SR", cd: "Suriname " },
  { mask: "+597-###-###", cc: "SR", cd: "Suriname" },
  { mask: "+211-##-###-####", cc: "SS", cd: "South Sudan" },
  { mask: "+239-##-#####", cc: "ST", cd: "Sao Tome and Principe" },
  { mask: "+503-##-##-####", cc: "SV", cd: "El Salvador" },
  { mask: "+1(721)###-####", cc: "SX", cd: "Sint Maarten" },
  { mask: "+963-##-####-###", cc: "SY", cd: "Syrian Arab Republic" },
  { mask: "+268-##-##-####", cc: "SZ", cd: "Swaziland" },
  { mask: "+1(649)###-####", cc: "TC", cd: "Turks & Caicos" },
  { mask: "+235-##-##-##-##", cc: "TD", cd: "Chad" },
  { mask: "+228-##-###-###", cc: "TG", cd: "Togo" },
  { mask: "+66-##-###-####", cc: "TH", cd: "Thailand " },
  { mask: "+66-##-###-###", cc: "TH", cd: "Thailand" },
  { mask: "+992-##-###-####", cc: "TJ", cd: "Tajikistan" },
  { mask: "+690-####", cc: "TK", cd: "Tokelau" },
  { mask: "+670-###-####", cc: "TL", cd: "East Timor" },
  { mask: "+670-77#-#####", cc: "TL", cd: "East Timor" },
  { mask: "+670-78#-#####", cc: "TL", cd: "East Timor" },
  { mask: "+993-#-###-####", cc: "TM", cd: "Turkmenistan" },
  { mask: "+216-##-###-###", cc: "TN", cd: "Tunisia" },
  { mask: "+676-#####", cc: "TO", cd: "Tonga" },
  { mask: "+90(###)###-####", cc: "TR", cd: "Turkey" },
  { mask: "+1(868)###-####", cc: "TT", cd: "Trinidad & Tobago" },
  { mask: "+688-90####", cc: "TV", cd: "Tuvalu " },
  { mask: "+688-2####", cc: "TV", cd: "Tuvalu" },
  { mask: "+886-#-####-####", cc: "TW", cd: "Taiwan" },
  { mask: "+886-####-####", cc: "TW", cd: "Taiwan" },
  { mask: "+255-##-###-####", cc: "TZ", cd: "Tanzania" },
  { mask: "+380(##)###-##-##", cc: "UA", cd: "Ukraine" },
  { mask: "+256(###)###-###", cc: "UG", cd: "Uganda" },
  { mask: "+44-##-####-####", cc: "UK", cd: "United Kingdom" },
  { mask: "+598-#-###-##-##", cc: "UY", cd: "Uruguay" },
  { mask: "+998-##-###-####", cc: "UZ", cd: "Uzbekistan" },
  { mask: "+39-6-698-#####", cc: "VA", cd: "Vatican City" },
  { mask: "+1(784)###-####", cc: "VC", cd: "Saint Vincent & the Grenadines" },
  { mask: "+58(###)###-####", cc: "VE", cd: "Venezuela" },
  { mask: "+1(284)###-####", cc: "VG", cd: "British Virgin Islands" },
  { mask: "+1(340)###-####", cc: "VI", cd: "US Virgin Islands" },
  { mask: "+84-##-####-###", cc: "VN", cd: "Vietnam" },
  { mask: "+84(###)####-###", cc: "VN", cd: "Vietnam" },
  { mask: "+678-##-#####", cc: "VU", cd: "Vanuatu " },
  { mask: "+678-#####", cc: "VU", cd: "Vanuatu" },
  { mask: "+681-##-####", cc: "WF", cd: "Wallis and Futuna" },
  { mask: "+685-##-####", cc: "WS", cd: "Samoa" },
  { mask: "+967-###-###-###", cc: "YE", cd: "Yemen " },
  { mask: "+967-#-###-###", cc: "YE", cd: "Yemen" },
  { mask: "+967-##-###-###", cc: "YE", cd: "Yemen" },
  { mask: "+27-##-###-####", cc: "ZA", cd: "South Africa" },
  { mask: "+260-##-###-####", cc: "ZM", cd: "Zambia" },
  { mask: "+263-#-######", cc: "ZW", cd: "Zimbabwe" },
  { mask: "+1(###)###-####", cc: ["US", "CA"], cd: "USA and Canada" },
] as const
